---
title: "P8131 Homework 5"
author: "Roxy Zhang"
date: "3/23/2022"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pscl) # for count model
```

## Question 1

```{r}
crab = read.table("data/HW5-crab.txt", header = TRUE)
```

```{r}
# Poisson model M1
m1 <- glm(
  Sa ~ W,
  family = poisson(link = log),
  data = crab)

summary(m1)

# Goodness of fit
# Deviance
m1_D = sum(residuals(m1, type = "deviance") ^ 2)

# Pearson chi-square
m1_G = sum(residuals(m1, type = "pearson") ^ 2)

m1_df = 173 - 2

1 - pchisq(m1_D, m1_df)
```

```{r}
# Poisson model M2
m2 <- glm(
  Sa ~ W + Wt,
  family = poisson(link = log),
  data = crab)

summary(m2)

# Goodness of fit
# Deviance
m2_D = sum(residuals(m2, type = "deviance") ^ 2)

# Pearson chi-square
m2_G = sum(residuals(m2, type = "pearson") ^ 2)

m2_df = 173 - 3

1 - pchisq(m2_D, m2_df)
```

```{r}
# check over-dispersion in M2

# residual of M2
m2_res = residuals(m2, type = "pearson")

# over-dispersion parameter
phi = m2_G / (173 - 3)

# half normal plot
plot(
  qnorm((173 + 1:173 + 0.5) / (2 * 173 + 1.125)),
  sort(abs(m2_res)),
  xlab='Expected Half-Normal Order Statistics', 
  ylab='Ordered Absolute Pearson Residuals')

abline(a = 0, b = 1)
abline(a = 0, b = sqrt(phi), lty = 2)

# fit model with constant over-dispersion
summary(m2, dispersion = phi)

# goodness of fit
p_value = 1 - pchisq(m2_G/phi, 170)
p_value # fit is good
```


## Question 2

```{r}
parasite = read.table("data/HW5-parasite.txt", header = T)

dim(parasite)
summary(parasite)

# check for categorical variable levels
unique(parasite$Area)
unique(parasite$Year)

m3 = glm(
  Intensity ~ factor(Area) + factor(Year) + Length,
  family = poisson(link = log), 
  data = parasite)

summary(m3)

exp(m3$coefficients)
```

```{r}
# Goodness of fit
m3_D = sum(residuals(m3, type = "deviance") ^ 2)
deviance(m3) # the same

m3_G = sum(residuals(m3, type = "pearson") ^ 2)

pchisq(deviance(m3), df.residual(m3), lower.tail = FALSE)
```

```{r}
# zero-inflated model
m4 =  zeroinfl(
  Intensity ~ factor(Area) +  factor(Year) + Length, 
  data = parasite)

summary(m4)

exp(m4$coefficients$count)
exp(m4$coefficients$zero)
```

